#!/usr/bin/env python3

P = 8
N_COEFFS   = (P + 1) * (P + 2) // 2      # 45
N_COEFFS_V = (2*P + 1) * (2*P + 2) // 2  # 180

def get_mem_idx(l, m):
    pos = 0
    for mm in range(m):
        pos += (P + 1 - mm)
    pos += (l - m)
    return pos * 2


def parity_sign(k):
    return 1.0 if (abs(k) % 2 == 0) else -1.0


def precalc_m2l():

    # Collect entries per target coefficient
    target_entries = {}
    for l in range(P + 1):
        for m in range(l + 1):
            target_entries[(l, m)] = []

    # Loop over source coefficients (n, k) with k in full range
    for n in range(P + 1):
        for k in range(-n, n + 1):

            source_mem_idx = get_mem_idx(n, abs(k))

            # Symmetry for k < 0
            if k < 0:
                c_sign_r = parity_sign(k)
                c_sign_i = -parity_sign(k)
            else:
                c_sign_r = 1.0
                c_sign_i = 1.0

            # Loop over translation harmonics
            for v_l in range(2*P):
                for v_m in range(-v_l, v_l + 1):

                    l_f = n + v_l
                    m_f = k + v_m

                    if m_f < 0:
                        continue

                    v_mem_idx = get_mem_idx(v_l, abs(v_m))

                    # Symmetry for v_m < 0
                    if v_m < 0:
                        v_sign_r = parity_sign(v_m)
                        v_sign_i = -parity_sign(v_m)
                    else:
                        v_sign_r = 1.0
                        v_sign_i = 1.0

                    # Complex multiplication signs:
                    # target_r += s_rr * V_r * c_r + s_ri * V_i * c_i
                    # target_i += s_ir * V_r * c_i + s_ii * V_i * c_r
                    s_rr = v_sign_r * c_sign_r
                    s_ri = -(v_sign_i * c_sign_i)
                    s_ir = v_sign_r * c_sign_i
                    s_ii = v_sign_i * c_sign_r

                    target_entries[(l_f, m_f)].append({
                        "ci": source_mem_idx,
                        "vi": v_mem_idx,
                        "s_rr": s_rr,
                        "s_ri": s_ri,
                        "s_ir": s_ir,
                        "s_ii": s_ii,
                    })

    # Serialize in CSL buffer order: outer m = 0..P, inner l = m..P
    offsets = []
    source_indices = []
    v_indices = []
    sign_rr = []
    sign_ri = []
    sign_ir = []
    sign_ii = []

    curr_offset = 0
    for m in range(P + 1):
        for l in range(m, P + 1):
            entry_list = target_entries[(l, m)]
            offsets.append(curr_offset)

            for entry in entry_list:
                source_indices.append(entry["ci"])
                v_indices.append(entry["vi"])
                sign_rr.append(entry["s_rr"])
                sign_ri.append(entry["s_ri"])
                sign_ir.append(entry["s_ir"])
                sign_ii.append(entry["s_ii"])

            curr_offset += len(entry_list)

    offsets.append(curr_offset)

    return offsets, source_indices, v_indices, sign_rr, sign_ri, sign_ir, sign_ii


def format_u16_array(name, values):
    n = len(values)
    items = ", ".join(str(int(v)) for v in values)
    return f"pub const {name} = [{n}]u16{{ {items} }};\n"


def format_f32_array(name, values):
    n = len(values)
    items = []
    for v in values:
        if v == 1.0:
            items.append("1.0")
        elif v == -1.0:
            items.append("-1.0")
        else:
            items.append(f"{v}")
    return f"pub const {name} = [{n}]f32{{ {', '.join(items)} }};\n"


def generate_csl():
    offsets, source_indices, v_indices, s_rr, s_ri, s_ir, s_ii = precalc_m2l()

    total_entries = len(source_indices)

    lines = []
    lines.append("// Auto-generated by generate_m2l_tables.py")
    lines.append("// Do not edit manually.")
    lines.append(f"// P = {P}, N_COEFFS = {N_COEFFS}, N_ENTRIES = {total_entries}")
    lines.append("")
    lines.append(f"pub const N_ENTRIES: u16 = {total_entries};")
    lines.append("")

    lines.append("// Offsets (CSR format) for each target coefficient (length = N_COEFFS + 1)")
    lines.append(format_u16_array("offsets", offsets))

    lines.append("// Source buffer index for each sparse entry (length = N_ENTRIES)")
    lines.append(format_u16_array("source_indices", source_indices))

    lines.append("// V buffer index for each sparse entry (length = N_ENTRIES)")
    lines.append(format_u16_array("v_indices", v_indices))

    lines.append("// Signs for complex multiplication (length = N_ENTRIES each)")
    lines.append("// target_r += sign_rr * V_r * c_r + sign_ri * V_i * c_i")
    lines.append("// target_i += sign_ir * V_r * c_i + sign_ii * V_i * c_r")
    lines.append(format_f32_array("sign_rr", s_rr))
    lines.append(format_f32_array("sign_ri", s_ri))
    lines.append(format_f32_array("sign_ir", s_ir))
    lines.append(format_f32_array("sign_ii", s_ii))

    with open("m2l_tables.csl", "w") as f:
        f.write("\n".join(lines))

    print(f"Generated m2l_tables.csl")
    print(f"  P = {P}")
    print(f"  N_COEFFS = {N_COEFFS}")
    print(f"  N_ENTRIES = {total_entries}")
    print(f"  offsets: {len(offsets)} elements")

    # Memory estimate
    mem_u16 = (len(offsets) + total_entries * 2) * 2
    mem_f32 = total_entries * 4 * 4
    total_mem = mem_u16 + mem_f32
    print(f"  Memory: {total_mem} bytes ({total_mem / 1024:.1f} KB)")


if __name__ == "__main__":
    generate_csl()
